# Generated by Django 4.0.2 on 2022-03-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_image_url_alter_blog_slug_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
