# Generated by Django 4.0.2 on 2022-03-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth_token',
            new_name='verification_token',
        ),
    ]
