# Generated by Django 4.0.2 on 2022-03-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_auth_token_user_verification_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_token',
            new_name='email_verification_token',
        ),
    ]
